name = "AirspeedVelocity"
uuid = "1c8270ee-6884-45cc-9545-60fa71ec23e4"
authors = ["Miles Cranmer <miles.cranmer@gmail.com>"]
version = "0.5.2"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlotlyKaleido = "f2990250-8cf9-495f-b13a-cce12b45703c"
PlotlyLight = "ca7969ec-10b3-423e-8d99-40f33abb42bf"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
BenchmarkTools = "1"
Comonicon = "1"
FilePathsBase = "0.9"
JSON3 = "1"
OrderedCollections = "1"
PlotlyKaleido = "2"
PlotlyLight = "0.6"
REPL = "1"
TestItems = "0.1"
julia = "1.8"
